### ISSUE TITLE
Docs feedback

### ISSUE THREAD

**Issue by MarekSuchanek** [IgorRosocha/labelord_IgorRosocha#3]
Documentation looks nice, just few improvements:

1. in order to build docs, you need to install something more than docs/requirements.txt otherwise you'll get `Could not import extension sphinx_click.ext (exception: No module named 'click')` (just mention it in the README.rst), also too many "python" in the command in README.rst
2. it is weird that you have still `0.3` in `setup.py` but release `0.5` (as well as on PyPI)

Please fix these so I can give you 5+1 points...

**Comment by IgorRosocha** [comment]
Thanks for the feedback, improvements implemented.

**Comment by MarekSuchanek** [comment]
The problem wasn't with installing `pip install sphinx-click` but instructing user to first install labelord or install at least all dependencies of labelord (can be in step 1 - download labelord)... like if you create empty venv and just follow steps in Documentation section of your README.rst ... it is really a detail, but important for people not so familiar with Python who want to read documentation (if RTD is down for example).

**Comment by IgorRosocha** [comment]
Got it - added hint to install labelord in first step of building the documentation.

Again, thank you very much for the feedback.

**Comment by MarekSuchanek** [comment]
OK, thanks
